name: flutter_app
description: Flutter demo application.
authors:
  - Hammad Tariq (hammadtariq.me@gmail.com)
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc for state management
  flutter_bloc: ^4.0.0
  # font awesome library.
  font_awesome_flutter: ^8.5.0
  # Value equality
  equatable: ^1.2.5
  # Service locator
  get_it: ^5.0.3

  # Functional programming in Dart.
  dartz: ^0.9.2

  # Local cache
  shared_preferences: ^0.5.12+4

  # Localization
  flutter_localizations:
    sdk: flutter
  # To add localized text.
  intl: ^0.16.0

  # Networking
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  connectivity: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true

