name: flutter_app
description: Flutter demo application.
authors:
  - Hammad Tariq (hammadtariq.me@gmail.com)
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Bloc for state management
  flutter_bloc: ^6.1.3
  # font awesome library.
  font_awesome_flutter: ^8.5.0
  # Value equality
  equatable: ^2.0.0
  # Service locator
  get_it: ^6.0.0
  # For Navigation and Themes.
  get:

  # Functional programming in Dart.
  dartz: ^0.9.2

  # Local cache
  shared_preferences: ^2.0.3

  # Localization
  flutter_localizations:
    sdk: flutter
  # To add localized text.
  intl: ^0.17.0

  # Networking
  data_connection_checker: ^0.3.4
  dio: ^3.0.10
  connectivity: ^3.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  uses-material-design: true
  generate: true

